version: '3.7'

services:
  nginx:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - backend

  db:
    image: mariadb
    restart: always
    ports:
      - "33060:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tenis-challenge
    volumes:
      - ../databases/db:/var/lib/mysql
    networks:
      - backend

  api:
    build:
      context: ./api/docker/php-fpm/
    volumes:
      - ./api:/var/www/html
    expose:
      - "8080"
    env_file:
      - ./api/.env
    environment:
      - VIRTUAL_HOST=api.localhost
      - VIRTUAL_PORT=8080
    networks:
      - backend

      
networks:
  backend:
    driver: bridge
      